import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import "@coinbase/onchainkit/styles.css";
import { cookieToInitialState } from "wagmi";
import { getConfig } from "@/lib/wagmi";
import { headers } from "next/headers";
import Headers from "@/components/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    getConfig(),
    headers().get("cookie"),
  );

  return (
    <html lang="en">
      <body
        className={inter.className}
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers initialState={initialState}>
          <div className="min-h-dvh flex flex-col">
            <Headers />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
