[tool.poetry]
name = "cdp-agent-trial"
version = "0.1.0"
description = "Coinbase CDP Agent Trial"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
langchain-openai = "*"
langchain-core = "*"
langgraph = "*"
cdp-sdk = "*"
cdp-langchain = "*"
python-dotenv = "*"
pydantic = "*"
fastapi = "*"
uvicorn = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
